#!/usr/bin/env ruby
# frozen_string_literal: true

require 'etc'

qemu = %W[
  -device virtio-iommu,granule=4k
  -device pcie-root-port,id=port2,slot=2
  -device pcie-root-port,id=port3,slot=3
  -device vmxnet3,bus=port1,mac=02:00:00:01:00:00,multifunction=on,netdev=hub0port0
  -device vmxnet3,addr=0x0.0x1,bus=port1,mac=02:00:00:01:01:00,netdev=hub1port0
  -device #{ARGV[0]},bus=port2,mac=02:00:00:01:00:01,netdev=hub0port1
  -device #{ARGV[0]},bus=port3,mac=02:00:00:01:01:01,netdev=hub1port1
  -netdev hubport,id=hub0port0,hubid=0 -netdev hubport,id=hub0port1,hubid=0
  -netdev hubport,id=hub1port0,hubid=1 -netdev hubport,id=hub1port1,hubid=1
]

exec(File.join(__dir__, 'x'), *qemu, *ARGV[1..])
