#!/bin/bash

d="$(dirname "${BASH_SOURCE[0]}")"
ip tuntap add mode tap multi_queue
ip link set tap0 up
ip address add 10.0.2.0 dev tap0
ip route add 10.0.2.1 dev tap0
echo $$ > "$d/var/pid"
exec "$d/x" -snapshot -device virtio-net,addr=0x0.0x1,bus=port1,netdev=n,rss=on -netdev tap,id=n,ifname=tap0,queues=4,script=no,downscript=no,vhost=on "$@"
